pipelines:
  default:
    - step:
        name: Run tests
        script:
          - python -m unittest discover tests/
  branches:
    master:
      - step:
          name: Run tests
          script:
            - python -m unittest discover tests/
      - step:
          name: Deploy to server
          deployment: production
          script:
            - rsync -a  -e "ssh -o StrictHostKeyChecking=no" ./ bitbucket@team12-19.studenti.fiit.stuba.sk:/var/www/python/logger